default:
  uri_lookup:
    performer:      "http://example.com/slowmo#ascribee"
    has_performer:  "http://example.com/slowmo#slowmo_0000001"
    uses_template:  "http://example.com/slowmo#slowmo_0000003"
    uses_ISR:       "http://example.com/slowmo#slowmo_0000002"
    rid_template:   "http://example.com/slowmo#template"
    spek:           "http://example.com/slowmo#slowmo_0000140"
    ISR:            "http://example.com/cpo#cpo_0000029"
    normative_comparator:  "http://example.com/slowmo#normative_comparator"
    prevention_framing:    "http://example.com/cpo#cpo_0000038"
    promotion_framing:     "http://example.com/cpo#cpo_0000037"
    performer_cardinality: "http://example.com/slowmo#performer_cardinality"
    time_cardinality:      "http://example.com/slowmo#time_cardinality"
    capability_barrier:    "http://example.com/slowmo#slowmo_0000132"
    prevention_focus:      "http://example.com/cpo#cpo_0000036"
    promotion_focus:       "http://example.com/cpo#cpo_0000035"
    perf_gap:              "http://example.com/slowmo#performance_gap"
    perf_trend_pos:        "http://example.com/slowmod#performance_trend_pos"
    perf_trend_neg:        "http://example.com/slowmod#performance_trend_neg"
    related_location:      "http://example.com/app#related_location"
    has_part:        "http://purl.obolibrary.org/obo/bfo#BFO_0000051"
    has_disposition: "http://purl.obolibrary.org/obo/RO_0000091"
    client_spek:     "http://example.com/app#clientname_spek"
  app_onto_url:      "http://example.com/app#"
  col_spec:
    id_cols:
      - performer
    perf_cols:
      - numerator
      - denominator
    time_col:
      - timepoint
