default:
  uri_lookup:
    performer:      "http://purl.obolibrary.org/obo/fio#FIO_0000001"
    spek:           "http://purl.obolibrary.org/obo/fio#SPEK"
    has_performer:  "http://purl.obolibrary.org/obo/fio#HasPerformer"
    uses_template:  "http://purl.obolibrary.org/obo/fio#UsesTemplate"
    uses_ISR:       "http://purl.obolibrary.org/obo/fio#UsesISR"
    rid_template:   "http://purl.obolibrary.org/obo/fio#RIDTemplate"
    spek:           "http://purl.obolibrary.org/obo/fio#Spek"
    ISR:            "http://purl.obolibrary.org/obo/fio#ISR"
    normative_comparator:  "http://purl.obolibrary.org/obo/fio#NormativeComparator"
    prevention_framing:    "http://purl.obolibrary.org/obo/fio#PreventionFraming"
    promotion_framing:     "http://purl.obolibrary.org/obo/fio#PromotionFraming"
    performer_cardinality: "http://purl.obolibrary.org/obo/fio#PerformerCardinality"
    time_cardinality:      "http://purl.obolibrary.org/obo/fio#TimeCardinality"
    capability_barrier:    "http://purl.obolibrary.org/obo/fio#CapbilityBarrier"
    prevention_focus:      "http://purl.obolibrary.org/obo/fio#PreventionFocus"
    promotion_focus:       "http://purl.obolibrary.org/obo/fio#PromotionFocus"
    negative_signal:       "http://purl.obolibrary.org/obo/fio#NegativeSignal"
    positive_signal:       "http://purl.obolibrary.org/obo/fio#PositiveSignal"
    perf_gap:              "http://purl.obolibrary.org/obo/fio#PerformanceGap"
    perf_trend_pos:        "http://purl.obolibrary.org/obo/fio#PerformanceTrendPositive"
    perf_trend_neg:        "http://purl.obolibrary.org/obo/fio#PerformanceTrendNegative"
    related_location:      "https://purl.obolibrary.org/need/definiton#RELATED_LOCATION"
    has_part:        "http://purl.obolibrary.org/obo/bfo#BFO_0000051"
    has_disposition: "http://purl.obolibrary.org/obo/RO_0000091"
    client_spek:     "https://inference.es/app/onto#IPLARC_SPEK"
  app_onto_url:      "https://inference.es/app/onto#"
  #output_dir: "/tmp/bstomach"
  #annotation_path = "example/count/annotations.r"
  col_spec:
    id_cols:
      - performer
    perf_cols:
      - numerator
      - denominator
    time_col:
      - timepoint
